### PR TITLE
#163081040: Design Dashboard. 

### PR DESCRIPTION
**Pull request by arthurarty**
**What does this PR do?**

Designs the dashboard the user will see once successfully logged in. 

**Description of the tasks to be completed?**
- Add navigation bar component. 
- Add navigation bar component to home view. 
- Add sidebar to dashboard. 

**How should this be manually tested?**
- Clone the repository
- git checkout ft-dashboard-163081040
- install dependencies using `yarn install`
- Run the app using `yarn start`
- The application should be running.
- Open browser and go to http://localhost:3000

**Screenshots**
image

**What are the relevant pivotal tracker stories?**
[#163081040](https://www.pivotaltracker.com/story/show/163081040)

### CODE REVIEW

**Review by kizzanaome — APPROVED** [review]
Please take a look at the Hound CI issues otherwise Good work

**Review by Luleherll — COMMENTED** [review]
Good work

**Review by okellogabrielinnocent — COMMENTED** [review]
Good work

**Review by okellogabrielinnocent — APPROVED** [review]

**Review by aayebare — APPROVED** [review]
this looks okay

**Pull request merged**
